apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  template:
    spec:
      containers:
      - name: app
        image: anand1516/gitops-demo:0.2.0

        env:
        - name: APP_VERSION
          value: "v0.2.0"
