apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 1
  selector: { matchLabels: { app: gitops-demo } }
  template:
    metadata: { labels: { app: gitops-demo } }
    spec:
      containers:
      - name: app
        image: <DOCKERHUB_USER>/gitops-demo:0.1.0
        ports: [{ containerPort: 8080 }]
        env:
        - name: APP_VERSION
          value: "v0.1.0"
